### ISSUE TITLE
Uncaught TypeError: undefined is not a function

### ISSUE THREAD

**Issue by raeffu** [stmichael/atom-ergonomic-cursor#4]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [ergonomic-cursor](https://github.com/stmichael/atom-ergonomic-cursor) package, v0.1.0
### Stack Trace

Uncaught TypeError: undefined is not a function

```
At /Users/rlaubscher/projects/dotfiles/atom/packages/ergonomic-cursor/lib/ergonomic-cursor.coffee:38

TypeError: undefined is not a function
    at IncrementalSelection.deactivate (/Users/rlaubscher/projects/dotfiles/atom/packages/ergonomic-cursor/lib/ergonomic-cursor.coffee:38:31)
    at /Users/rlaubscher/projects/dotfiles/atom/packages/ergonomic-cursor/lib/ergonomic-cursor.coffee:26:21
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:236:32
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at DisplayBuffer.module.exports.DisplayBuffer.emitDidChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:313:20)
    at DisplayBuffer.module.exports.DisplayBuffer.updateScreenLines (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1592:19)
    at DisplayBuffer.module.exports.DisplayBuffer.handleTokenizedBufferChange (/Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:1551:12)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/display-buffer.js:5:61
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
```
### Commands

```
     -0:17.1.0 core:save (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
     -0:15.5.0 core:save-as (ol.tree-view.full-menu.list-tree.has-collapsable-children.focusable-panel)
  7x -0:08.4.0 ergonomic-cursor:move-down (atom-text-editor.editor.is-focused)
     -0:07.3.0 editor:move-to-beginning-of-next-paragraph (atom-text-editor.editor.is-focused)
     -0:06.6.0 ergonomic-cursor:move-up (atom-text-editor.editor.is-focused)
     -0:06.2.0 editor:move-to-end-of-line (atom-text-editor.editor.is-focused)
  7x -0:05.6.0 editor:move-to-beginning-of-word (atom-text-editor.editor.is-focused)
     -0:03.7.0 ergonomic-cursor:move-right (atom-text-editor.editor.is-focused)
     -0:03.2.0 ergonomic-cursor:activate-selection (atom-text-editor.editor.is-focused)
  6x -0:03.0 ergonomic-cursor:move-left (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "one-light-ui",
      "one-light-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atomatigit, v1.5.4
ergonomic-cursor, v0.1.0
file-icons, v1.6.9
language-diff, v0.3.1
language-elixir, v0.5.2
language-haml, v0.21.0
language-latex, v0.6.1
latex, v0.25.1
linter, v1.5.0
linter-jshint, v1.1.5

# Dev
No dev packages
```

**Comment by stmichael** [comment]
Should be fixed in 0.2.0.
