### ISSUE TITLE
Uncaught Error: Emitter has been disposed

### ISSUE THREAD

**Issue by edrubin** [stmichael/atom-ergonomic-cursor#5]
Activate selection (which I really like) dies when I use the following sequence of actions.
1. Activate selection (using shortcut)
2. Split selections into lines (using shortcut)
3. Exit selection using escape key
4. Activate selection (using shortcut)

I also tried exiting out of selection via the activate selection shortcut, but found the same error.

**Atom Version**: 1.7.4
**System**: Mac OS X 10.11.5
**Thrown From**: [ergonomic-cursor](https://github.com/stmichael/atom-ergonomic-cursor) package, v0.2.0
### Stack Trace

Uncaught Error: Emitter has been disposed

```
At /Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:77

Error: Emitter has been disposed
    at Emitter.module.exports.Emitter.on (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:77:15)
    at Cursor.module.exports.Cursor.onDidChangePosition (/Applications/Atom.app/Contents/Resources/app.asar/src/cursor.js:45:27)
    at IncrementalSelection.activate (/Users/edwardarubin/.atom/packages/ergonomic-cursor/lib/ergonomic-cursor.coffee:11:36)
    at Object.module.exports.activateSelection (/Users/edwardarubin/.atom/packages/ergonomic-cursor/lib/ergonomic-cursor.coffee:58:46)
    at atom-text-editor.atom.commands.add.ergonomic-cursor:activate-selection (/Users/edwardarubin/.atom/packages/ergonomic-cursor/lib/ergonomic-cursor.coffee:38:16)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```
### Commands

```
     -0:24.7.0 zen:toggle (atom-text-editor.editor.is-focused)
     -0:22.7.0 ergonomic-cursor:activate-selection (atom-text-editor.editor.is-focused)
 10x -0:21.9.0 ergonomic-cursor:move-down (atom-text-editor.editor.is-focused)
     -0:20.3.0 editor:move-to-beginning-of-next-paragraph (atom-text-editor.editor.is-focused)
     -0:18.6.0 editor:split-selections-into-lines (atom-text-editor.editor.is-focused)
  2x -0:17.5.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:15.2.0 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -0:05.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:03.7.0 core:move-to-top (atom-text-editor.editor.is-focused)
     -0:01.0 ergonomic-cursor:activate-selection (atom-text-editor.editor.is-focused)
  2x -0:00.6.0 ergonomic-cursor:move-down (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.gfm": [
        "txt"
      ],
      "source.r": [
        "rout"
      ]
    },
    "disabledPackages": [
      "markdown-preview",
      "block-cursor",
      "terminal-plus",
      "antialiased",
      "omni-ruler",
      "latexer",
      "seti-icons",
      "language-markdown",
      "ink"
    ],
    "ignoredNames": [
      ".git",
      ".svn",
      ".DS_Store"
    ],
    "openEmptyEditorOnStart": false,
    "packagesWithKeymapsDisabled": [
      "mathjax-wrapper",
      "simple-center-screen"
    ],
    "themes": [
      "native-ui",
      "proton-kai"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
Sublime-Style-Column-Selection, v1.5.1
Zen, v0.16.4
atom-clock, v0.0.8
autocomplete-python, v1.7.2
character-table, v0.4.3
color-picker, v2.1.1
cursor-blink-interval, v0.3.1
cursor-indicator, v1.2.7
ergonomic-cursor, v0.2.0
file-icons, v1.7.11
file-types, v0.5.1
highlight-selected, v0.11.2
language-julia, v0.6.0
language-latex, v0.6.1
language-matlab-octave, v0.1.1
language-r, v0.4.1
language-stata, v0.1.0
latex-autocomplete, v0.4.2
latextools, v0.8.0
markdown-preview-plus, v2.4.0
markdown-scroll-sync, v2.1.2
markdown-themeable-pdf, v1.0.1
minimap, v4.23.5
minimap-cursorline, v0.1.0
native-ui, v0.18.2
open-recent, v5.0.0
overscroll, v0.1.0
pdf-view, v0.50.0
pigments, v0.26.2
proton-kai, v0.1.0
tablr, v1.3.0
wordcount, v2.6.0

# Dev
No dev packages
```

**Comment by stmichael** [comment]
I don't really understand the source of this problem. As I understand, 'Split selections into lines' creates a cursor for each line in the current selection. Fact of the matter is that the selection of this package isn't intended to work with multiple cursors at the moment. I can't tell when this package will support multiple cursors. I'll take a look at it soon.
